services:
  hotel_agent_toolbox:
    image:  us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    platform: linux/amd64
    environment:
      - CLOUDSDK_CONFIG=/.gcp/config
      - GOOGLE_APPLICATION_CREDENTIALS=/.gcp/config/application_default_credentials.json
    volumes:
      - ./travel_agent/remote_agents/hotel_agent/toolbox:/config
      - $HOME/.config/gcloud:/.gcp/config
    command: [ "toolbox", "--tools-file", "/config/tools.yml", "--address", "0.0.0.0", "--port", "5001" ]
    network_mode: service:travel_agent
  travel_remote_agent:
    build:
      context: ./travel_agent
      dockerfile: Dockerfile
    env_file: .env
    entrypoint: ["adk", "api_server", "--a2a", "--host", "0.0.0.0", "--allow_origins", "http://localhost:8000", "--port", "8001", "/app/remote_agents"]
    network_mode: service:travel_agent
  travel_agent:
    hostname: travel_agent
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    entrypoint: ["adk", "web", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"
