services:
  toolbox:
    image:  us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:latest
    hostname: toolbox
    platform: linux/amd64
    ports:
      - "5001:5001"
    environment:
      - CLOUDSDK_CONFIG=/.gcp/config
      - GOOGLE_APPLICATION_CREDENTIALS=/.gcp/config/application_default_credentials.json
    volumes:
      - ./toolbox:/config
      - $HOME/.config/gcloud:/.gcp/config
    command: [ "toolbox", "--tools-file", "/config/tools.yml", "--address", "0.0.0.0", "--port", "5001" ]
    networks:
      - tool-network
  hotet_agent:
    build:
      context: ./hotel_agent
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - TOOLBOX_URL=http://toolbox:5001
    ports:
      - "8000:8000"
    entrypoint: ["adk", "web"]
    networks:
      - tool-network
    image: hotel-agent
networks:
  tool-network:
